name: CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
          
    - name: Restore Solution
      run: dotnet restore Kinetq.ServiceProvider.sln
      
    - name: Build Solution
      run: dotnet build Kinetq.ServiceProvider.sln 
      
    - name: Test Solution
      run: dotnet test Kinetq.ServiceProvider.sln
      
    - name: Publish Kinetq.ServiceProvider
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          PROJECT_FILE_PATH: Kinetq.ServiceProvider/Kinetq.ServiceProvider.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
